---
- name: 'Commit changes to uci'
  community.openwrt.uci:
    cmd: commit
  listen: openwrt_uci_commit

- name: 'Restart system'
  community.openwrt.service:
    name: system
    state: restarted
  when: "not ansible_facts['is_chroot']"
  listen: openwrt_restart_system

- name: 'Restart ntpd'
  community.openwrt.service:
    name: sysntpd
    state: restarted
  when: "not ansible_facts['is_chroot']"
  listen: openwrt_restart_ntpd

- name: 'Restart uhttpd'
  community.openwrt.service:
    name: uhttpd
    state: restarted
  when: "not ansible_facts['is_chroot']"
  listen: openwrt_restart_uhttpd

- name: 'Restart cron'
  community.openwrt.service:
    name: cron
    state: restarted
  when: "not ansible_facts['is_chroot']"
  listen: openwrt_restart_cron
